services:
  dev: # The name of the service, can be anything
    image: image_todo-front_dev # Declares which image to use
    build:
      context: .
      dockerfile: Dockerfile_dev
    ports: # Declares the ports to publish
      - 3210:5173
    volumes:
      - ./:/usr/src/app # The path can be relative, so ./ is enough to say "the same location as the docker-compose.yml"
    container_name: container_todo-front_dev
  debug-helper:
    image: busybox
    command: sleep 3600
    depends_on:
      - dev
# docker compose  -f docker-compose_dev.yml up
# docker compose -f docker-compose_dev.yml up -d (-d for detached)
# docker compose -f docker-compose_dev.yml down (if started with -d)

# docker compose -f docker-compose_dev.yml run debug-helper wget -O - http://dev:5173
